version: "3.8"

x-environment: &environment
  - CONFIG=config
  - CACHE_URL=redis
  - CACHE_PASSWORD=
  - ENVIRONMENT=production
  - HOST_IP=0.0.0.0
  - CATALOG_SERVICE=catalog_service
  - ORDER_SERVICE=order_service

#x-healthcheck: &healthcheck
#  test: curl --fail -s http://localhost:5000/ping || exit 1 #Need to start leader election or notify frontend.
#  interval: 30s
#  timeout: 5s
#  retries: 1

services:
  catalog_service:
    image: catalog
    container_name: catalog_service
    environment: *environment
    build: ./catalog_service/
    ports:
      - 5297:5297
    volumes:
      - ./catalog_service/output.json:/catalog_service/output.json
    networks:
      - lab

  order_service:
    image: order
    container_name: order_service
    environment: *environment
#      - HTTP_PORT=6298
#      - GRPC_PORT=6297
    build: ./order_service
    ports:
      - 6297:6297
      - 6298:6298
    volumes:
      - ./order_service/transaction_log.csv:/order_service/transaction_log.csv
    depends_on:
      - redis
      - catalog_service
    networks:
      - lab
#    healthcheck: *healthcheck

  frontend_service:
    image: frontend
    container_name: frontend_service
    environment: *environment
    build: ./frontend_service
    ports:
      - 8081:8081
    depends_on:
      - order_service
    networks:
      - lab

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./cache_data:/data
    networks:
      - lab


networks:
  lab:
    external: true
