version: "3.8"

x-environment: &environment
  - HOST_IP=0.0.0.0
  - CATALOG_SERVICE=catalog_service
  - ORDER_SERVICE=order_service

services:
  catalog_service:
    image: catalog
    container_name: catalog_service
    environment: *environment
    build: ./catalog_service/
    ports:
      - 5297:5297
    volumes:
      - ./catalog_service/output.json:/catalog_service/output.json
    networks:
      - lab

  order_service:
    image: order
    container_name: order_service
    environment: *environment
    build: ./order_service
    ports:
      - 6297:6297
    volumes:
      - ./order_service/transaction_log.csv:/order_service/transaction_log.csv
    depends_on:
      - catalog_service
    networks:
      - lab

  frontend_service:
    image: frontend
    container_name: frontend_service
    environment: *environment
    build: ./frontend_service
    ports:
      - 8081:8081
    depends_on:
      - order_service
    networks:
      - lab

networks:
  lab:
    external: true
