version: "3.8"

x-environment: &environment
  - CONFIG=config
  - CACHE_URL=redis
  - CACHE_PASSWORD=
  - ENVIRONMENT=production
  - HOST_IP=0.0.0.0
  - CATALOG_SERVICE=catalog_service
  - ORDER_SERVICE=order_service

x-healthcheck: &healthcheck
  test: curl --fail -s http://localhost:5000/ping || exit 1
  interval: 30s
  timeout: 5s
  retries: 1

services:
  catalog_service:
    image: catalog
    container_name: catalog_service
    environment: *environment
    build: ./catalog_service/
    ports:
      - 5297:5297
    volumes:
      - ./catalog_service/output.json:/catalog_service/output.json
    networks: # please remove networks if you want to run AWS
      - lab
    healthcheck: *healthcheck

  order_service_1:
    image: order
    container_name: order_service_1
    environment:
      - ID=1
      - CONFIG=config
      - CACHE_URL=redis
      - CACHE_PASSWORD=
      - ENVIRONMENT=production
      - HOST_IP=0.0.0.0
      - CATALOG_SERVICE=catalog_service
      - HTTP_PORT=6298
      - GRPC_PORT=6297
    build: ./order_service
    ports:
      - 6297:6297
      - 6298:6298
    volumes:
      - ./order_service/transaction_log_1.csv:/order_service/transaction_log_1.csv
    depends_on:
      - redis
      - catalog_service
    networks: # please remove networks if you want to run AWS
      - lab
    healthcheck: *healthcheck

  order_service_2:
    image: order
    container_name: order_service_2
    environment:
      - ID=2
      - CONFIG=config
      - CACHE_URL=redis
      - CACHE_PASSWORD=
      - ENVIRONMENT=production
      - HOST_IP=0.0.0.0
      - CATALOG_SERVICE=catalog_service
      - HTTP_PORT=7298
      - GRPC_PORT=7297
    build: ./order_service
    ports:
      - 7297:7297
      - 7298:7298
    volumes:
      - ./order_service/transaction_log_2.csv:/order_service/transaction_log_2.csv
    depends_on:
      - redis
      - catalog_service
    networks: # please remove networks if you want to run AWS
      - lab
    healthcheck: *healthcheck

  order_service_3:
    image: order
    container_name: order_service_3
    environment:
      - ID=3
      - CONFIG=config
      - CACHE_URL=redis
      - CACHE_PASSWORD=
      - ENVIRONMENT=production
      - HOST_IP=0.0.0.0
      - CATALOG_SERVICE=catalog_service
      - HTTP_PORT=8298
      - GRPC_PORT=8297
    build: ./order_service
    ports:
      - 8297:8297
      - 8298:8298
    volumes:
      - ./order_service/transaction_log_3.csv:/order_service/transaction_log_3.csv
    depends_on:
      - redis
      - catalog_service
    networks: # please remove networks if you want to run AWS
      - lab
    healthcheck: *healthcheck

  frontend_service:
    image: frontend
    container_name: frontend_service
    environment: *environment
    build: ./frontend_service
    ports:
      - 8081:8081
    depends_on:
      - redis
      - order_service_1
      - order_service_2
      - order_service_3
    networks: # please remove networks if you want to run AWS
      - lab
    healthcheck: *healthcheck

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./cache_data:/data
    networks: # please remove networks if you want to run AWS
      - lab
    healthcheck: *healthcheck

networks: # please remove networks if you want to run AWS
  lab:
    external: true
