# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import trade.order_handler_pb2 as order__handler__pb2


class OrderHandlerStub(object):
    """The Request Handler service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Order = channel.unary_unary(
                '/order_handler.OrderHandler/Order',
                request_serializer=order__handler__pb2.Request.SerializeToString,
                response_deserializer=order__handler__pb2.Response.FromString,
                )


class OrderHandlerServicer(object):
    """The Request Handler service definition.
    """

    def Order(self, request, context):
        """Executes a Trade for the client and communicates the success of it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderHandlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Order': grpc.unary_unary_rpc_method_handler(
                    servicer.Order,
                    request_deserializer=order__handler__pb2.Request.FromString,
                    response_serializer=order__handler__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'order_handler.OrderHandler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderHandler(object):
    """The Request Handler service definition.
    """

    @staticmethod
    def Order(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order_handler.OrderHandler/Order',
            order__handler__pb2.Request.SerializeToString,
            order__handler__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
