# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_handler.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15request_handler.proto\x12\x0frequest_handler\"#\n\rLookupRequest\x12\x12\n\nstock_name\x18\x01 \x01(\t\"F\n\x0cTradeRequest\x12\x12\n\nstock_name\x18\x01 \x01(\t\x12\x14\n\x0ctrade_volume\x18\x02 \x01(\x02\x12\x0c\n\x04type\x18\x03 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\x02\x32\x9c\x01\n\x0eRequestHandler\x12\x45\n\x06Lookup\x12\x1e.request_handler.LookupRequest\x1a\x19.request_handler.Response\"\x00\x12\x43\n\x05Trade\x12\x1d.request_handler.TradeRequest\x1a\x19.request_handler.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'request_handler_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOOKUPREQUEST._serialized_start=42
  _LOOKUPREQUEST._serialized_end=77
  _TRADEREQUEST._serialized_start=79
  _TRADEREQUEST._serialized_end=149
  _RESPONSE._serialized_start=151
  _RESPONSE._serialized_end=178
  _REQUESTHANDLER._serialized_start=181
  _REQUESTHANDLER._serialized_end=337
# @@protoc_insertion_point(module_scope)
